services:
  proxy:
    image: caddy:2.9.1
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: http://proxy:80
      KC_HEALTH_ENABLED: true
    depends_on:
      keycloak_db:
        condition: service_healthy

  keycloak_db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      timeout: 1s
      retries: 10

  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18000:8000"
    volumes:
      - .:/app
    depends_on:
      django_db:
        condition: service_healthy

  django_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
      retries: 10
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
